### ISSUE TITLE
ReferenceError: File is not defined

### ISSUE THREAD

**Issue by wotori** [aml2610/react-painter#29]
Got this error after importing this module.
Used raw code as in example.
My react version is "latest".
I also use next.js, mb here the reason.
But It was warking before I reloaded the page.
![image](https://user-images.githubusercontent.com/10486621/144939353-225b0736-df7e-4a65-9546-f3d204fbd5a8.png)

**Comment by aml2610** [comment]
Hey! Sorry to hear you're having trouble. I am not really familiar with next.js but if you're still having troubles I can take a look. Did you manage to make it work in the end?

**Comment by aml2610** [comment]
I'll close for now, assuming you managed to fix. Feel free to re-open if not.

**Comment by Karyum** [comment]
The error comes from [this line of code](https://github.com/aml2610/react-painter/blob/master/src/ReactPainter.tsx#L52), Next.js renders server side, and during the process a lot of the web APIs are not available like `document` `window` and the `File` instance.
